language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: Qxe/mhAH1jWtdPvYBHuipluX539o3ALDde54feWCk8l0Ful1oVt9O9Fx2bZFWOWn6aSDWDgR5CkX4IB0mCJ/VYiCsKhZUMiBVwW/rB/sUSSuj/W8NenkOQk8etIth236ZNq2LHk9asr4YFKv+PsgtBX5411SLJANEsCoIJPqhf4q7ZHVsJAXsjkTsQmQyUZJPq5O/jsRIHWt/ZsS0DuUxx5uQBKbNpzFl58QzlpX9UsPRV745Z0UizuypIrwaYPbwYsOXpjunKlGQaX+Lyj/W1J8tfLeITUxDfdGnIEL4KiQX0LVD9OIBB2BDh4SwfPFJ2PRapjyP6wrm75lr949RFHw4nLrg75WQtO3VeRvPKAnbZO0ia0BcOKlKmqL+ALVnnk6NBe1VDxTO/xLAXE7obWH3xKzjoVF0MyWACupHxcbwszIH1zTE+RIlFEf4YxRJOJ38NBP5bohIwqLRghSagCqn2293/rq4CcL9t+zWYHANnP7qDxd9hDnKeS8rKdxzc3LzTd08QbbdbWpfN7FNS2eqVHfEXWRwHssWRXn8PsQAiVN+u5BH8AM50amZxn1UdId+VhX50qqF91OMIeq15YJKkaAqOUwA8h9yNiDfng/GLnNoUL7N5Nhn957j8eTwO2KjaTeKTvKqEYcSl9YJnYAqP0cPXH8aFaWl2uNtS4=
